foarkarswurdlist-gui/src/main/java/org/fa/foarkarswurdlist/jsf/StdwController.java
package org.fa.foarkarswurdlist.jsf;

import jakarta.enterprise.inject.spi.CDI;
import jakarta.faces.context.ExternalContext;
import jakarta.faces.context.FacesContext;
import jakarta.inject.Inject;
import org.fa.foarkarswurdlist.ejb.StdwCrudBean;
import org.fa.foarkarswurdlist.ejb.StdwCrudService;
import org.fa.foarkarswurdlist.jpa.listeners.CrudAware;
import org.fryske_akademy.jpa.AbstractEntity;
import org.fryske_akademy.jsf.NewSupportingLazyController;
import org.fryske_akademy.jsf.lazy.NewSupportingLazyModel;
import org.fryske_akademy.services.Auditing;
import org.fryske_akademy.services.CrudReadService;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.Serial;
import java.util.List;
import org.fryske_akademy.jsf.util.JsfUtil;
import org.primefaces.event.RowEditEvent;

public abstract class StdwController<T extends AbstractEntity, R extends NewSupportingLazyModel<T>> extends NewSupportingLazyController<T, R> {

    @Inject
    private transient StdwCrudService crudWriteService;
    @Inject
    @StdwCrudBean
    private transient Auditing auditing;
    

    @Serial
    private void readObject(ObjectInputStream inputStream) throws IOException, ClassNotFoundException {
        inputStream.defaultReadObject();
        crudWriteService = CDI.current().select(StdwCrudService.class).get();
        auditing = CDI.current().select(Auditing.class, CrudAware.STDW_ANNOTATION).get();
    }

    @Override
    public CrudReadService getCrudReadService() {
        return auditing;
    }

    @Override
    public StdwCrudService getCrudWriteService() {
        return crudWriteService;
    }

    @Override
    public void destroy(T entity) {
        try {
            super.destroy(entity);
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e.getMessage());
        }
    }

    @Override
    public T save(RowEditEvent event) {
        try {
            return super.save(event);
        } catch (Exception e) {
            // handled insuper
        }
        return (T) event.getObject();
    }

    public boolean isRememberTableState() {
        return super.isRememberTableState() && !FILTERING.equals(
                FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get(STATE));
    }

    @Override
    protected String newRowOnLastPage(String table) {
        return "lastPage('" + table + "');scrollDown('.ui-layout-unit-content');";
    }

    @Override
    protected String newRowOnCurrentPage(String table) {
        return "";
    }

    @Override
    public String gotoPageContaining(T entity) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    protected void fillCopy(T newEntity, T selected) {
    }

    @Override
    protected boolean useFilterMechanism() {
        return true;
    }

    @Override
    public List<String> complete(String query) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public static void redirectToServletPath(String servletPath) throws IOException {
        ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
        externalContext.redirect(externalContext.getRequestContextPath() + servletPath);
    }
}

foarkarswurdlist-gui/src/main/webapp/parts/List.xhtml
<!DOCTYPE html>
<html
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <ui:composition template="/template.xhtml">

        <ui:define name="title">
            <h:outputText value="LemmaParts"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <c:set var="ctrl" value="#{lemmaPartController}"/>
            <h:form id="Form"><p:commandButton styleClass="noEnter" tabindex="-1" value="" onclick="return false;"/>
                <p:remoteCommand name="buttons" update="download createButton lemmaButton deleteButton copyButton"/>
                <p:panel id="buttonpanel">
                    <p:link href="#" onclick="saveAll();return false;" value="#{bundle.saveAll}" styleClass="saveall" title="#{bundle['saveall.msg']}"/>
                    <p:link onclick="PF('datalist').clearFilters();PF('datalist').filter()" value="clear filters" styleClass="saveall"/>
                    <p:commandButton value="#{bundle.Create}" actionListener="#{ctrl.editNew('datalist')}"
                                     disabled="#{ctrl.newEntity!=null }" id="createButton" rendered="#{sessionBean.mayEdit()}"
                                     update="@this datalist" styleClass="nieuw" />
                    <p:commandButton id="copyButton" update="@this datalist" accesskey="c" rendered="#{sessionBean.mayEdit()}"
                     value="#{bundle.Copy}" actionListener="#{ctrl.copy('datalist')}" disabled="#{empty ctrl.selected}"/>
                    <p:commandButton id="lemmaButton" value="Lemma" action="#{ctrl.showLemma(ctrl.selected)}" disabled="#{empty ctrl.selected}"/>
                    <p:commandButton id="download" title="download" icon="fa fa-download" ajax="false"  disabled="#{lazyLemmaPart.rowCount > 10000}">
                        <p:dataExporter type="csv"  target="datalist" fileName="paradigmas" pageOnly="false" />
                    </p:commandButton>
                    <p:selectBooleanCheckbox value="#{ctrl.useOr}" itemLabel="#{bundle.of}" style="margin-left: 5px;">
                        <p:ajax update="datalist"/>
                    </p:selectBooleanCheckbox>
                </p:panel>
                <p:sticky target="buttonpanel">
                    <p:autoUpdate/>
                </p:sticky>
                <h:panelGroup>
                     <p:dataTable allowUnsorting="true" filterEvent="change" id="datalist" value="#{ctrl.lazyModel}" var="item"
                                 selection="#{ctrl.selected}" sortMode="multiple" selectionMode="single"
                                 paginator="true" editable="#{sessionBean.mayEdit()}" editingRow="#{sessionBean.mayEdit()}"
                                 rowKey="#{ctrl.getRowKey(item.id)}" filteredValue="#{lazyLemmaPart.filtered}"
                                 rows="#{settings.rowsInTable}" lazy="true" draggableColumns="true" resizableColumns="true" liveResize="true" widgetVar="datalist"
                                 rowsPerPageTemplate="10,20,30,40,50" multiViewState="#{ctrl.rememberTableState}"
                                 currentPageReportTemplate="{startRecord}-{endRecord} of {totalRecords}"
                                 paginatorTemplate="{RowsPerPageDropdown} {CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
                                 >

                        <ui:include src="/datatable.xhtml"/>

                        <p:column class="row-editor" exportable="false" rendered="#{sessionBean.mayEdit()}">
                            <p:rowEditor/>
                        </p:column>
                        <p:column rendered="#{sessionBean.mayEdit()}" sortBy="#{item.id}" filterBy="#{item.id}" filterValue="#{lazyLemmaPart.filters['id']}">
                            <f:facet name="header">
                                <h:outputText value="id"/>
                            </f:facet>
                            <f:facet name="filter">
                                <p:inputText value="#{lazyLemmaPart.filters['id']}" onchange="PF('datalist').filter();"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </p:column>
                        <p:column sortBy="#{item.part}" filterBy="#{item.part}" filterValue="#{lazyLemmaPart.filters['part']}">
                            <f:facet name="header">
                                <h:outputText value="part"/>
                            </f:facet>
                            <p:cellEditor>
                                <f:facet name="output">
                                    <h:outputText value="#{item.part}"/>
                                </f:facet>
                                <f:facet name="input">
                                    <p:inputText onchange="changed($(this))" id="part" value="#{item.part}"  />
                                </f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column filterBy="#{item.pos}" filterValue="#{lazyLemmaPart.filters['pos']}">
                            <f:facet name="header">
                                <h:outputText value="pos"/>
                            </f:facet>
                            <p:cellEditor>
                                <f:facet name="output">
                                    <h:outputText  value="#{item.pos}"/>
                                </f:facet>
                                <f:facet name="input">
                                    <p:selectOneMenu onchange="changed($(this))" id="pos" value="#{item.pos}">
                                        <f:selectItem itemLabel="#{bundle.SelectOneMessage}" value="#{null}"></f:selectItem>
                                        <f:selectItems value="#{ctrl.getPOS()}" var="pos" itemLabel="#{pos}" itemValue="#{pos}"></f:selectItems>
                                    </p:selectOneMenu>
                                </f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column sortBy="#{item.base}" filterBy="#{item.base}" filterValue="#{lazyLemma.filters['base']}" width="50px">
                            <f:facet name="filter">
                                <p:triStateCheckbox value="#{lazyLemma.filters['base']}" onchange="PF('datalist').filter();" />
                            </f:facet>
                            <f:facet name="header">
                                <h:outputText value="base" title="basis/hoofdlemma"/>
                            </f:facet>
                            <p:cellEditor>
                                <f:facet name="output">
                                    <h:outputText value="#{item.base}"/>
                                </f:facet>
                                <f:facet name="input">
                                    <h:inputHidden value="#{item.base}"/>
                                    <h:selectBooleanCheckbox onchange="changed($(this))" onclick="$(this).prev().val(this.checked)" id="base" value="#{item.base}"/>
                                </f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column sortBy="#{item.lemma}" filterBy="#{item.lemma}" filterValue="#{lazyLemmaPart.filters['lemma']}">
                            <f:facet name="header">
                                <h:outputText value="lemma"/>
                            </f:facet>
                            <p:cellEditor>
                                <f:facet name="output">
                                    <h:outputText  value="#{item.lemma}"/>
                                </f:facet>
                                <f:facet name="input">
                                    <p:autoComplete onchange="changed($(this))" id="lemmaId" value="#{item.lemma}" completeMethod="#{lemmaController.complete}"/>
                                </f:facet>
                            </p:cellEditor>
                        </p:column>
                        <p:column rendered="#{sessionBean.mayEdit()}" style="width: 40px">
                            <p:commandButton icon="fa fa-trash" actionListener="#{ctrl.destroy(item)}" update="datalist">
                                <p:confirm header="#{bundle.akkoord}" message="#{ctrl.deleteTitle()}" icon="fa fa-exclamation" />
                            </p:commandButton>

                        </p:column>
                    </p:dataTable>
                </h:panelGroup>
            </h:form>

        </ui:define>
    </ui:composition>

</html>